# Generated by Django 4.2.1 on 2023-07-31 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vizualicion_episodios_usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto', models.BooleanField(default=False)),
                ('episodio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.episodios')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='usuarios_animes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('fecha_agregado', models.DateField(null=True)),
                ('comentario', models.CharField(max_length=100)),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.anime')),
                ('estado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.estados')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuarios')),
            ],
        ),
    ]
