# Generated by Django 4.2.1 on 2023-11-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios_animes',
            name='estado_id',
        ),
        migrations.AddField(
            model_name='usuarios_animes',
            name='estado',
            field=models.CharField(blank=True, choices=[('planeados', 'Planeados'), ('proceso', 'En Proceso'), ('completados', 'Completados'), ('abandonados', 'Abandonados'), ('espera', 'En Espera')], default='planeados', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuarios_animes',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
