# Generated by Django 4.2.1 on 2023-11-13 21:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('relaciones', '0002_remove_usuarios_animes_estado_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios_animes',
            name='fecha_agregado',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
