# Generated by Django 4.2.1 on 2023-11-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relaciones', '0004_alter_usuarios_animes_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios_animes',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
