# Generated by Django 4.2.1 on 2023-11-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relaciones', '0005_alter_usuarios_animes_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios_animes',
            name='estado',
            field=models.CharField(blank=True, choices=[('planeados', 'Planeados'), ('proceso', 'En Proceso'), ('completados', 'Completados'), ('abandonados', 'Abandonados'), ('espera', 'En Espera')], max_length=50, null=True),
        ),
    ]
