# Generated by Django 4.2.1 on 2023-07-31 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_collation='utf8mb4_unicode_ci', max_length=255, null=True)),
                ('sinopsis', models.TextField(null=True)),
                ('tipo', models.CharField(choices=[('Anime', 'Anime'), ('Película', 'Película')], default='Anime', max_length=50)),
                ('año_lanzamiento', models.DateField(null=True)),
                ('debut', models.CharField(max_length=100, null=True)),
                ('duracion', models.IntegerField(null=True)),
                ('clasificacion_edad', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG_13'), ('R', 'R'), ('R18+', 'R18+')], max_length=6, null=True)),
                ('poster_url', models.URLField(max_length=100, null=True)),
                ('banner_url', models.URLField(max_length=100, null=True)),
                ('trailer_url', models.URLField(max_length=100, null=True)),
                ('total_episodios', models.IntegerField(null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Episodios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_episodio', models.PositiveIntegerField(null=True)),
                ('titulo_episodio', models.CharField(max_length=100, null=True)),
                ('duracion', models.IntegerField(null=True)),
                ('fecha_lanzamiento', models.DateField(null=True)),
                ('sinopsis_episodio', models.TextField(null=True)),
                ('imagen_url_episodio', models.URLField(max_length=100, null=True)),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=15, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudios_animacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estudio', models.CharField(max_length=100, null=True)),
                ('fundacion', models.DateField(null=True)),
                ('pais', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Generos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_genero', models.CharField(max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video_server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('ads', models.IntegerField(default=0)),
                ('url_episodios', models.URLField(max_length=100)),
                ('allow_mobile', models.BooleanField()),
                ('code', models.URLField(max_length=100)),
                ('episodio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.episodios')),
            ],
        ),
        migrations.CreateModel(
            name='Download_Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_server', models.CharField(max_length=50)),
                ('download_url', models.URLField()),
                ('episodio_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.episodios')),
            ],
        ),
        migrations.CreateModel(
            name='Atributos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_atributo', models.CharField(max_length=100, null=True)),
                ('valor_atributo', models.CharField(max_length=100, null=True)),
                ('anime_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.anime')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='estudio_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='animes.estudios_animacion'),
        ),
        migrations.AddField(
            model_name='anime',
            name='genero_id',
            field=models.ManyToManyField(to='animes.generos'),
        ),
    ]
