# Generated by Django 4.2.1 on 2023-09-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_alter_episodios_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='order',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
