# Generated by Django 4.2.1 on 2023-10-02 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0005_alter_episodios_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episodios',
            name='numero_episodio',
            field=models.FloatField(null=True),
        ),
    ]
