# Generated by Django 4.2.1 on 2023-07-31 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('password', models.CharField(max_length=64, null=True)),
                ('fecha_registro', models.DateField(null=True)),
                ('pais', models.CharField(max_length=40, null=True)),
                ('avatar_url', models.URLField(max_length=100, null=True)),
                ('descripcion_personal', models.CharField(max_length=555, null=True)),
            ],
        ),
    ]
