# Generated by Django 4.2.1 on 2023-11-06 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuarios_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='is_staff',
        ),
    ]
