# Generated by Django 4.2.1 on 2023-11-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuarios_date_joined_usuarios_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='avatar_url',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
