# Generated by Django 4.2.1 on 2023-11-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuarios_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='avatar_url',
            field=models.ImageField(null=True, upload_to='usuarios/avatar'),
        ),
    ]
